### ISSUE TITLE
Problem with the demo file

### ISSUE THREAD

**Issue by LouLaurent** [omar178/Emotion-recognition#30]
I encounter 2 problems when i test the demo file.
First, the version of openCV in the requirements text file doesn't exist, so i change the version :
**opencv_python==4.2.0.32**

Then, when i try to launch the demo, i have this error : 
_Using TensorFlow backend.
Traceback (most recent call last):
  File "real_time_video.py", line 1, in <module>
    from keras.preprocessing.image import img_to_array
  File "C:\Users\Lou Laurent\AppData\Local\Programs\Python\Python38-32\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\Lou Laurent\AppData\Local\Programs\Python\Python38-32\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\Lou Laurent\AppData\Local\Programs\Python\Python38-32\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\Lou Laurent\AppData\Local\Programs\Python\Python38-32\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "C:\Users\Lou Laurent\AppData\Local\Programs\Python\Python38-32\lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "C:\Users\Lou Laurent\AppData\Local\Programs\Python\Python38-32\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'_

Can you help me with this ?
Thanks,
Lou

**Comment by jaimerodric** [comment]
In terms of opencv, I have not had any problem with python 3.6.8.
The other problem I have not solved, so I am still waiting for help. I don't know if it is needed to install tensorflow(in that case, which version), because it does not appear on the requirements.txt

**Comment by LouLaurent** [comment]
I solve the problem, Tensorflow is not compatible with Python 32 bits, so you need to download Python 64 bits !
