### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.python'

### ISSUE THREAD

**Issue by JSdheerajkumar** [omar178/Emotion-recognition#36]

**Comment by AgnesLeem** [comment]
conda install tensorflow

**Comment by Murmelmaus** [comment]
Hi, I have the same problem. I am working with Anaconda, py3.8. Installed are tensorflow 2.4.0, openscv-python 4.5.1.48, keras 2.4.3,  pandas 1.2.0, numpy 1.19.15, imutils 0.5.3, scikit_learn 0.24.0. When I run real_time_video.py I get the following message:
Using TensorFlow backend.
Traceback (most recent call last):
  File "D:/Repos-Adriana/Emotion-recognition-master/real_time_video.py", line 1, in <module>
    from keras.preprocessing.image import img_to_array
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

Is there already a solution for that? Many thanks!
