### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by ShitBro369** [omar178/Emotion-recognition#54]
when i run 'real_time_video.py'
error as fllow:(what can i do)
Traceback (most recent call last):
  File "C:/Users/Lenovo/PycharmProjects/Emotion-recognition/real_time_video.py", line 29, in <module>
    frame = imutils.resize(frame,width=300)
  File "D:\anaconda\lib\site-packages\imutils\convenience.py", line 69, in resize
    (h, w) = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by lrtyui** [comment]
请问怎么解决？我也遇到这个错误了
